services:
  gluetun:
    image: gluetun-custom:latest
    pull_policy: never
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - LOG_LEVEL=debug
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_PORT_FORWARDING=on
      - PORT_FORWARD_ONLY=on
      - SERVER_COUNTRIES=Spain
      - OPENVPN_USER=$OPENVPN_USER
      - OPENVPN_PASSWORD=$OPENVPN_PASSWORD
      - PROTOCOL=udp
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - VPN_PORT_FORWARDING_UP_COMMAND=python3 /gluetun/forward_port_torrent.py {{PORTS}}
    volumes:
      - /home/tofu/docker/gluetun:/gluetun
    ports:
      - 7878:7878 # radarr
      - 8888:8888 # qbittorrent
      - 8989:8989 # sonarr
      - 9696:9696 # prowlarr
      - 6881:6881
      - 6881:6881/udp
      - 3000:3000
      - 9091:9091
    restart: unless-stopped
    networks:
      - mediaserver

  qbittorrent:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    image: lscr.io/linuxserver/qbittorrent:latest
    pull_policy: always
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - WEBUI_PORT=8888
      - QBITTORRENT_WEBUI_LISTEN_ADDRESS=0.0.0.0  # Escuchar en todas las interfaces
    volumes:
      - /home/tofu/docker/qbittorrent/config:/config
      - /mnt/evo/Downloads:/Downloads
    restart: unless-stopped
    depends_on:
      - gluetun
    network_mode: "service:gluetun"  # Hereda la red del contenedor gluetun
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8888/ || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3

  jellyfin:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    image: lscr.io/linuxserver/jellyfin:latest
    pull_policy: always
    container_name: jellyfin
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/tofu/docker/jellyfin:/config
      - /mnt/evo/MediaServer:/MediaServer
    restart: unless-stopped


  sonarr:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    image: lscr.io/linuxserver/sonarr:latest
    pull_policy: always
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/tofu/docker/sonarr:/config
      - /mnt/evo/MediaServer/Series:/MediaServer/Series
      - /mnt/evo/Downloads:/Downloads
    network_mode: "service:gluetun"            
    restart: unless-stopped
    
  radarr:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    image: lscr.io/linuxserver/radarr:latest
    pull_policy: always
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/tofu/docker/radarr:/config
      - /mnt/evo/MediaServer/Movies:/MediaServer/Movies
      - /mnt/evo/Downloads:/Downloads
    restart: unless-stopped
    network_mode: "service:gluetun"
      
  prowlarr:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    image: lscr.io/linuxserver/prowlarr:latest
    pull_policy: always
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/tofu/docker/prowlarr/data:/config
    restart: unless-stopped


  jellyseerr:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    image: fallenbagel/jellyseerr:latest
    pull_policy: always
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Madrid
    volumes:
      - /home/tofu/docker/jellyseerr:/app/config
    ports:
      - 5055:5055
    networks:
      - mediaserver
    restart: unless-stopped

  bazarr:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    image: lscr.io/linuxserver/bazarr:latest
    pull_policy: always
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/tofu/docker/bazarr/data:/config
      - /mnt/evo/MediaServer:/MediaServer
    ports:
      - 6767:6767
    networks:
      - mediaserver         
    restart: unless-stopped

  unpackerr:
    image: golift/unpackerr:latest
    container_name: unpackerr
    volumes:
      - /mnt/evo/Downloads:/Downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - UN_SONARR_0_URL=http://gluetun:8989
      - UN_SONARR_0_API_KEY=${SONARR_API_KEY}
      - UN_RADARR_0_URL=http://gluetun:7878
      - UN_RADARR_0_API_KEY=${RADARR_API_KEY}
    restart: unless-stopped
    networks:
      - mediaserver
    depends_on:
      - gluetun

  cloudflare:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    container_name: cloudflare-media
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    networks:
      - mediaserver
    environment:
      - TUNNEL_TOKEN=$TUNNEL_TOKEN

networks:
  mediaserver:
    driver: bridge
    name: mediaserver