services:
  gluetun:
    image: gluetun-custom:latest
    pull_policy: always
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - LOG_LEVEL=debug
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_PORT_FORWARDING=on
      - PORT_FORWARD_ONLY=on
      - SERVER_COUNTRIES=Spain
      - OPENVPN_USER=$OPENVPN_USER
      - OPENVPN_PASSWORD=$OPENVPN_PASSWORD

      - PROTOCOL=udp
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - VPN_PORT_FORWARDING_UP_COMMAND=python3 /gluetun/forward_port_torrent.py {{PORTS}}
    volumes:
      - /home/tofu/docker/gluetun:/gluetun
    ports:
      - 7878:7878 # radarr
      - 8888:8888 # qbittorrent
      - 8989:8989 # sonarr
      - 9696:9696 # prowlarr
      - 6881:6881
      - 6881:6881/udp
      - 3000:3000
      - 9091:9091
    restart: unless-stopped
    networks:
      - mediaserver

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    pull_policy: always
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - WEBUI_PORT=8888
      - QBITTORRENT_WEBUI_LISTEN_ADDRESS=0.0.0.0  # Escuchar en todas las interfaces
    volumes:
      - /home/tofu/docker/qbittorrent/config:/config
      - /mnt/IronWolf/Downloads:/Downloads
    restart: unless-stopped
    depends_on:
      - gluetun
    network_mode: "service:gluetun"  # Hereda la red del contenedor gluetun
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8888/ || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3

  
  plex:
    image: lscr.io/linuxserver/plex:latest
    pull_policy: always
    container_name: plex
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
    volumes:
      - /home/tofu/docker/plex:/config
      - /mnt/IronWolf/MediaServer:/MediaServer
    restart: unless-stopped

  tautulli:
    image: ghcr.io/tautulli/tautulli:v2.15.1
    container_name: tautulli
    restart: unless-stopped
    volumes:
      -  /home/tofu/docker/tautulli:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - 8181:8181
    networks:
      - mediaserver

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    pull_policy: always
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/tofu/docker/sonarr:/config
      - /mnt/IronWolf/MediaServer/Series:/MediaServer/Series
      - /mnt/IronWolf/Downloads:/Downloads
    network_mode: "service:gluetun"            
    restart: unless-stopped
    
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    pull_policy: always
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/tofu/docker/radarr:/config
      - /mnt/IronWolf/MediaServer/Movies:/MediaServer/Movies
      - /mnt/IronWolf/Downloads:/Downloads
    restart: unless-stopped
    network_mode: "service:gluetun"
      
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    pull_policy: always
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/tofu/docker/prowlarr/data:/config
    restart: unless-stopped


  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    pull_policy: always
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/tofu/docker/overseerr:/config
    ports:
      - 5055:5055
    networks:
      - mediaserver
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    pull_policy: always
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/tofu/docker/bazarr/data:/config
      - /mnt/IronWolf/MediaServer:/MediaServer
    ports:
      - 6767:6767
    networks:
      - mediaserver         
    restart: unless-stopped

  # jellyfin:
  #   image: lscr.io/linuxserver/jellyfin:latest
  #   container_name: jellyfin
  #   network_mode: host
  #   devices:
  #     - /dev/dri:/dev/dri
  #   #networks:
  #   #  - mediaserver
  #   ports:
  #     - 8096:8096
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/UTC
  #   volumes:
  #     - /home/tofu/docker/jellyfin:/config
  #     - /mnt/IronWolf/MediaServer:/MediaServer
  #   restart: unless-stopped

  # jellyseerr:
  #   image: ghcr.io/fallenbagel/jellyseerr:latest
  #   container_name: jellyseerr
  #   environment:
  #     - JELLYFIN_URL=http://jellyfin:8096
  #     - JELLYFIN_API_KEY=${JELLYFIN_API_KEY}
  #     - DB_TYPE=sqlite
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/Madrid
  #   volumes:
  #     - /home/tofu/docker/jellyseerr/config:/app/config
  #   ports:
  #     - 5056:5055
  #   networks:
  #     - mediaserver
  #   restart: unless-stopped

  cloudflare:
    container_name: cloudflare-media
    image: cloudflare/cloudflared:2024.12.1
    restart: unless-stopped
    command: tunnel run
    networks:
      - mediaserver
    environment:
      - TUNNEL_TOKEN=$TUNNEL_TOKEN

networks:
  mediaserver:
    driver: bridge
    name: mediaserver