services:


  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - "127.0.0.1:5678:5678"
    labels:
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - N8N_TRUST_PROXY=true
      - N8N_TRUSTED_PROXIES=loopback,linklocal,uniquelocal,127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - DB_SQLITE_POOL_SIZE=5
      - N8N_RUNNERS_ENABLED=true
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    volumes:
      - n8n_data:/home/node/.n8n
      - /home/tofu/docker/n8n/local-files:/files
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5678/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    networks:
      - n8n
      - portainer_bridge

  mcp-proxy:
    container_name: mcp-proxy
    image: ghcr.io/tbxark/mcp-proxy:latest
    restart: unless-stopped
    ports:
      - 9090:9090
    networks:
      - n8n
    environment:
      SSE_URL: ${HA_URL}
      API_ACCESS_TOKEN: ${HA_TOKEN}
    volumes:
      - /home/tofu/docker/mcp-proxy/config.json:/config/config.json:ro

  cloudflare:
    container_name: cloudflare_n8n
    image: cloudflare/cloudflared:latest
    pull_policy: always
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    depends_on:
      - n8n
    networks:
      - n8n
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}

volumes:
  n8n_data:
  traefik_data:
  postgres_n8n_data:

networks:
  n8n:
    driver: bridge
    name: n8n
  portainer_bridge:
    external: true