services:
  nginxproxymanager:
    container_name: nginx-proxymanager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '40080:80' # Public HTTP Port
      - '40443:443' # Public HTTPS Port
      - '40081:81' # Admin Web Port
    environment:
      TZ: "Madrid/Spain"
      DISABLE_IPV6: 'true'
    volumes:
      - /home/tofu/docker/nginxproxymanager/data:/data
      - /home/tofu/docker/letsencrypt:/etc/letsencrypt